name: Example of date based version
# yyyymmdd.i where i is a counter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >$GITHUB_OUTPUT
      - name: get counter
        id: counter
        run: |
          LAST_RELEASE=$(gh release view --json=tagName | jq -r '.tagName')
          LAST_DATE=$(echo $LAST_RELEASE|sed 's/\..*$//')
          LAST_COUNTER=$(echo $LAST_RELEASE|sed 's/.*\.//')
          if [ "$LAST_DATE" = "$DATE" ]
          then
            echo "counter=$(expr 1 '+' $LAST_COUNTER)" >$GITHUB_OUTPUT
          else
            echo "counter=1" >$GITHUB_OUTPUT
          fi
        env:
          DATE: ${{ steps.date.outputs.date }}
          GH_TOKEN: ${{ github.token }}
      - name: get version
        id: version
        run: |
          echo "version=${{ steps.date.outputs.date }}.${{ steps.counter.outputs.counter }}" >$GITHUB_OUTPUT
      - name: echo version
        run: |
          echo $VERSION
        env:
          VERSION: $${{ steps.version.outputs.version }}
