name: Example of date based version
# yyyymmdd.i where i is a counter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: get counter
        id: counter
        run: |
          LAST_RELEASE=$(gh release view --json=tagName | jq -r '.tagName')
          LAST_DATE=$(echo $LAST_RELEASE|sed 's/\..*$//')
          LAST_COUNTER=$(echo $LAST_RELEASE|sed 's/.*\.//')
          if [ "$LAST_DATE" = "$DATE" ]
          then
            echo "::set-output name=counter::$(expr 1 '+' $LAST_COUNTER)"
          else
            echo "::set-output name=counter::1"
          fi
        env:
          DATE: ${{ steps.date.outputs.date }}
      - name: get version
        id: version
        run: |
          echo ${{ steps.date.outputs.date }}.${{ steps.counter.outputs.counter }}
