name: Show date
# To check timezone

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  echo-date:
    runs-on: ubuntu-latest
    steps:
      - name: date
        run: |
          echo "date=$(TZ=$TIME_ZONE date +'%Y%m%d%H%M%S')" >$GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        env:
          TIME_ZONE: JST-9
